### PR TITLE
Updated ReadMe - Section 13 Clima App - Add details on iOS physical device

### PR DESCRIPTION
**Pull request by Cyrille-Dakhlia**
Update README.md on "Section 13 Clima App" to add details on running the app on an iOS physical device, with changes that need to be made in order to match the updates from Apple iOS permissions, and the geolocator flutter package new version.

### CODE REVIEW

**Comment by DetainedDeveloper** [comment]
@Cyrille-Dakhlia Thank you for your contribution, there was no way for me to add the iOS part. Because I merged the older pull request, I'm getting a merge conflict, can you please take a pull of the latest version and send a new pull request? I would really appreciate it, thank you again.

**Comment by Cyrille-Dakhlia** [comment]
Hi @DetainedDeveloper , of course, I saw the pending pull request and already planned to update mine after you would merge that PR, I should have put a comment on my PR to say it, I'll don't miss it next time ^^
I'll update it later today!

**Comment by DetainedDeveloper** [comment]
@Cyrille-Dakhlia No worries! Take your time. And Thank you very much for your contribution!

**Comment by Cyrille-Dakhlia** [comment]
@DetainedDeveloper My pleasure and, should I say, thank you for your initiative in this contribution in the first place, that's greatly appreciated 🙏😉

**Comment by DetainedDeveloper** [comment]
@Cyrille-Dakhlia Thank you for your contribution, I have reviewed and merged your pull request.

**Comment by DetainedDeveloper** [comment]
@Cyrille-Dakhlia You're welcome, it's always a pleasure to contribute to the community 😄

**Pull request merged**
